// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReservationSystem.Infrastructure.Persistence;

#nullable disable

namespace ReservationSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415193531_SeedUsers200")]
    partial class SeedUsers200
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Desk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Desks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Desk A1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Desk A2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Desk A3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Desk B1"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Desk B2"
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DeskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DeskId", "Status")
                        .HasDatabaseName("IX_Reservations_DeskId_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("DeskId", "Status"), new[] { "StartAt", "EndAt" });

                    b.ToTable("Reservations", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Reservations_Dates", "[EndAt] > [StartAt]");

                            t.HasCheckConstraint("CHK_Reservations_Status", "[Status] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Anna Kowalska"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maria Nowak"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Katarzyna Wiśniewska"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Małgorzata Wójcik"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Agnieszka Kowalczyk"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Barbara Kamińska"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ewa Lewandowska"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Elżbieta Zielińska"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Zofia Szymańska"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Teresa Woźniak"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Magdalena Dąbrowska"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Joanna Kozłowska"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Janina Mazur"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Krystyna Jankowska"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Danuta Kwiatkowska"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Monika Krawczyk"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Beata Kaczmarek"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Marta Piotrowska"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Dorota Grabowska"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Julia Pawłowska"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Aleksandra Michalska"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Halina Król"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Jadwiga Wieczorek"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Jolanta Jabłońska"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Grażyna Wróbel"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Paulina Nowakowska"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Natalia Majewska"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Karolina Olszewska"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Justyna Stępień"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Edyta Malinowska"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Alicja Jaworska"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Urszula Adamczyk"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Iwona Dudek"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Renata Nowicka"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Beata Pawlak"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Agata Witkowska"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Aneta Walczak"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Izabela Sikora"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Sylwia Rutkowska"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Patrycja Michalak"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Emilia Szewczyk"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Weronika Ostrowska"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Kinga Baran"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Lucyna Tomaszewska"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Janina Zalewska"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Bożena Pietrzak"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Wiesława Marciniak"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Marzena Wróblewska"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Gabriela Jasińska"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Bogumiła Zawadzka"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Jan Kowalski"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Andrzej Nowak"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Piotr Wiśniewski"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Krzysztof Wójcik"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Stanisław Kowalczyk"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Tomasz Kamiński"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Paweł Lewandowski"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Józef Zieliński"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Marcin Szymański"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Marek Woźniak"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Michał Dąbrowski"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Grzegorz Kozłowski"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Jerzy Mazur"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Tadeusz Jankowski"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Adam Kwiatkowski"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Łukasz Krawczyk"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Zbigniew Kaczmarek"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Ryszard Piotrowski"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Dariusz Grabowski"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Henryk Pawłowski"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Mariusz Michalski"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Kazimierz Król"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Wojciech Wieczorek"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Robert Jabłoński"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Mateusz Wróbel"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Marian Nowakowski"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Rafał Majewski"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Jacek Olszewski"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Janusz Stępień"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Mirosław Malinowski"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Maciej Jaworski"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Sławomir Adamczyk"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Jarosław Dudek"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Kamil Nowicki"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Wiesław Pawlak"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Roman Witkowski"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Władysław Walczak"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Jakub Sikora"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Edward Rutkowski"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Mieczysław Michalak"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Damian Szewczyk"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Przemysław Ostrowski"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Sebastian Baran"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Arkadiusz Tomaszewski"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Antoni Zalewski"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Stefan Pietrzak"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Zygmunt Marciniak"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Igor Wróblewski"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Artur Jasiński"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Witold Zawadzki"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Helena Bąk"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Irena Włodarczyk"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Karolina Borkowska"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Marta Czarnecka"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Olga Sawicka"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Wanda Sokołowska"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Rozalia Maciejewska"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Kinga Kubiak"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Cecylia Kucharska"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mariola Wilk"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Sabina Wysocka"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Leokadia Lis"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Amelia Szczepańska"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Oliwia Kaźmierczak"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Nadia Andrzejak"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Kornelia Przybylska"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Lidia Głowacka"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Malwina Kania"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Daria Mrozowska"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Anita Krajewska"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nikola Urbańska"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Sandra Sadowska"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Adriana Ziółkowska"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Klaudia Sobczak"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Kamila Laskowska"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Blanka Kołodziej"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Malina Zakrzewska"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Sara Brzezińska"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Melania Makowska"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Aurelia Borowska"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Sonia Kurek"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Diana Markowska"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Eliza Mazurek"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Rozalia Kopała"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Judyta Tomczak"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Faustyna Wasilewska"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Marcelina Bielecka"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Michalina Kośmider"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Inga Szymczak"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Kalina Górecka"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Liwia Chmielewska"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Bianka Kaczmarczyk"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Gaja Czarnecka"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Iga Kowal"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Nela Bednarek"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Kaja Wrona"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Pola Murawska"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Ida Marszałek"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Elena Piekarska"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Róża Sowińska"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Błażej Bąk"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Konrad Włodarczyk"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Hubert Borkowski"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Daniel Czarnecki"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Adrian Sawicki"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Dominik Sokołowski"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Filip Maciejewski"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Gabriel Kubiak"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Julian Kucharski"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Krystian Wilk"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Szymon Wysocki"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Igor Lis"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Wiktor Szczepański"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Oliwier Kaźmierczak"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Alan Andrzejak"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Oskar Przybylski"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Cyprian Głowacki"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Gracjan Kania"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Maksymilian Mrozowski"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Nikodem Krajewski"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Kajetan Urbański"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Tymon Sadowski"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Bruno Ziółkowski"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Cezary Sobczak"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Fabian Laskowski"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Franciszek Kołodziej"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Gustaw Zakrzewski"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Ignacy Brzeziński"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Leon Makowski"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Marcel Borowski"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Maurycy Kurek"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Natan Markowski"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Olaf Mazurek"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Patryk Kopała"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Remigiusz Tomczak"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Samuel Wasilewski"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Teodor Bielecki"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Tymoteusz Kośmider"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Aleksander Szymczak"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Bartosz Górecki"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Dawid Chmielewski"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Eryk Kaczmarczyk"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Gerard Czarnecki"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Ireneusz Kowal"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Janusz Bednarek"
                        },
                        new
                        {
                            Id = 196,
                            Name = "Konstanty Wrona"
                        },
                        new
                        {
                            Id = 197,
                            Name = "Ludwik Murawski"
                        },
                        new
                        {
                            Id = 198,
                            Name = "Mikołaj Marszałek"
                        },
                        new
                        {
                            Id = 199,
                            Name = "Norbert Piekarski"
                        },
                        new
                        {
                            Id = 200,
                            Name = "Oktawian Sowiński"
                        });
                });

            modelBuilder.Entity("ReservationSystem.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("ReservationSystem.Domain.Entities.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReservationSystem.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Desk");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
